// scripts/generate-api-docs.ts
//
// Regenerates the API reference under content/apis/ from OpenAPI specs.
//
// Spec sources are chosen to avoid the failure mode that has bitten this repo
// twice: pointing at a branch of a repository nobody is watching.
//
// - Turbo reads from the running services' own /openapi.json (the document
//   their /api-docs Swagger UI loads). The ardriveapp/turbo-*-service repos
//   were made private on 2026-08-28 and their committed specs were years
//   stale, which broke the build.
// - ar-io-node reads from `main`, the released branch. It previously read from
//   `openapi-update`, a non-default branch last touched 2025-09-16, which was
//   missing six endpoints and the whole Rate Limiting tag.
//
// These are spec *sources*, not the base URLs shown in examples: those are
// applied as a `servers` override in src/lib/openapi.ts.
import { promises as fs } from 'node:fs';
import path from 'node:path';

const openApiMap: Record<string, {
  openapi: string;
  name: string;
}> = {
  'ar-io-node': {
    name: 'ar.io Node',
    openapi: 'https://raw.githubusercontent.com/ar-io/ar-io-node/refs/heads/main/docs/openapi.yaml',
  },
  'turbo/upload-service': {
    name: 'Upload Service',
    openapi: 'https://upload.ardrive.io/openapi.json',
  },
  'turbo/payment-service': {
    name: 'Payment Service',
    openapi: 'https://payment.ardrive.io/openapi.json',
  },
};

/**
 * Marker Fumadocs writes into every page it generates. Hand-authored files in
 * content/apis (the section `index.mdx` files and every `meta.json`) never
 * carry it, which is what makes the stale-page sweep below safe.
 */
const GENERATED_MARKER = 'This file was generated by Fumadocs';

/**
 * Delete pages left behind by a previous run whose tag no longer exists in the
 * spec.
 *
 * `generateFiles` overwrites what it produces but never removes anything, so a
 * retired tag's page lingered indefinitely. The obvious fix — wiping the output
 * directory first — is not safe here: `index.mdx` and `meta.json` in these
 * directories are hand-maintained. So only files carrying the generated marker
 * are considered, and only those the current run did not just write.
 */
async function removeStaleGeneratedPages(
  outputDir: string,
  writtenPaths: Set<string>,
): Promise<string[]> {
  let entries: string[];
  try {
    entries = await fs.readdir(outputDir);
  } catch {
    return [];
  }

  const removed: string[] = [];
  for (const entry of entries) {
    if (!entry.endsWith('.mdx')) continue;

    const filePath = path.join(outputDir, entry);
    if (writtenPaths.has(path.resolve(filePath))) continue;

    const content = await fs.readFile(filePath, 'utf-8');
    if (!content.includes(GENERATED_MARKER)) continue;

    await fs.rm(filePath);
    removed.push(entry);
  }
  return removed;
}

/**
 * Add newly generated pages to the directory's `meta.json`.
 *
 * These `pages` arrays are hand-ordered and lead with `"..."`, so a new tag
 * would otherwise surface above the established entries instead of alongside
 * them — five new payment-service tags landed at the top of the sidebar that
 * way. New slugs are appended, existing order is left alone, and entries that
 * no longer resolve are reported rather than deleted: some are deliberate
 * (separators, folder references) and Fumadocs ignores the rest.
 */
async function reconcileMeta(
  outputDir: string,
  generatedSlugs: string[],
): Promise<{ added: string[]; stale: string[] }> {
  const metaPath = path.join(outputDir, 'meta.json');

  let meta: { pages?: string[] } & Record<string, unknown>;
  try {
    meta = JSON.parse(await fs.readFile(metaPath, 'utf-8'));
  } catch {
    return { added: [], stale: [] };
  }
  if (!Array.isArray(meta.pages)) return { added: [], stale: [] };

  const listed = new Set(meta.pages);
  const added = generatedSlugs.filter((slug) => !listed.has(slug));

  // Anything listed that is neither a separator (`---Label---`), the `...`
  // wildcard, an exclusion (`!name`), nor a file/directory that exists.
  const stale: string[] = [];
  for (const entry of meta.pages) {
    if (entry === '...' || entry.startsWith('---') || entry.startsWith('!')) continue;
    const slug = entry.replace(/^\.\.\./, '');
    const exists =
      (await fs.stat(path.join(outputDir, `${slug}.mdx`)).catch(() => null)) ??
      (await fs.stat(path.join(outputDir, slug)).catch(() => null));
    if (!exists) stale.push(entry);
  }

  if (added.length > 0) {
    meta.pages = [...meta.pages, ...added];
    await fs.writeFile(metaPath, `${JSON.stringify(meta, null, 2)}\n`);
  }
  return { added, stale };
}

(async () => {
  const { generateFiles } = await import('fumadocs-openapi');
  const { createOpenAPI } = await import('fumadocs-openapi/server');

  for (const [key, openapi] of Object.entries(openApiMap)) {
    const outputDir = path.resolve(`./content/apis/${key}`);
    const openApi = createOpenAPI({
      input: [openapi.openapi],
      disableCache: true,
    });

    // `beforeWrite` is the only place the full output list is exposed, and it
    // runs before anything hits disk — so capture it there and use it to tell
    // this run's pages apart from leftovers.
    const writtenPaths = new Set<string>();

    await generateFiles({
      input: openApi,
      output: `./content/apis/${key}/`,
      includeDescription: true,
      per: 'tag',
      beforeWrite(files) {
        for (const file of files) writtenPaths.add(path.resolve(file.path));
      },
      frontmatter: (title: string) => {
        // Fix title capitalization
        if (title.toLowerCase() === 'ar n s') return { title: 'ArNS' };
        if (title.toLowerCase() === 'ar io') return { title: 'ar.io' };
        if (title.toLowerCase() === 'ar io node') return { title: 'ar.io Node' };
        // the x402 payment standard is always lowercase
        if (title.toLowerCase() === 'x402') return { title: 'x402' };
        return { title };
      },
    });

    const generatedSlugs = [...writtenPaths]
      .filter((file) => file.endsWith('.mdx'))
      .map((file) => path.basename(file, '.mdx'))
      .filter((slug) => slug !== 'index')
      .sort();

    const removed = await removeStaleGeneratedPages(outputDir, writtenPaths);
    const { added, stale } = await reconcileMeta(outputDir, generatedSlugs);

    console.log(`${key}: ${generatedSlugs.length} page(s) from ${openapi.openapi}`);
    if (removed.length > 0) console.log(`  removed stale: ${removed.join(', ')}`);
    if (added.length > 0) console.log(`  added to meta.json: ${added.join(', ')}`);
    if (stale.length > 0) {
      console.warn(`  meta.json lists missing entries (left in place): ${stale.join(', ')}`);
    }
  }
})();
