name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Build Docs Portal
        run: |
          cd docs
          yarn install --frozen-lockfile
          yarn build
          cd ..

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PUBLIC_SITE }}"
          channelId: live
          entryPoint: docs/src/.vuepress/dist